project:
  type: book
  output-dir: docs

book:
  title: "Data Mining"
  author: "Thiyanga S. Talagala"
  date: "10/11/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - ch2.qmd
    - ch3.qmd
    - ch4.qmd
    - ch5.qmd
    - ch6.qmd
    - ch7.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

